# Required services to run Wolfia on a local machine

version: '3.7'

services:
  dev-postgres:
    image: napstr/wolfia-postgres:12
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - ROLE=wolfia
      - DB=wolfia

  dev-redis:
    image: redis:5-alpine
    restart: always
    entrypoint:
      - redis-server
      - --appendonly
      - "yes"
    ports:
      - 127.0.0.1:6380:6379
    sysctls:
      - net.core.somaxconn=511   # container was spitting out a warning telling us to do this
