install: true  # skips unnecessary "gradle assemble" install step

services:
- docker

addons:
  sonarcloud:
    organization: "wolfiabot"
    token:
      secure: "qSMbFlI4AHiHsce4AwvMox7ADANggADV0WUEgupwq35qUetG1BIb6zA0GcL9rdv6paTRevks1K69fSC1hum8xsgOUBLlaiG1FIScskIxq7tXgZ2qk5C3BXMihoTxx9ledjn5cdsudqG+VvCXMzomlnPElmBTGTomqzuWOvGYjRfx9OCVdscEqaulDHI7s4fRkT4up+Pl6GEZpYtt898HelraLErvUwLESCH2SIi+VnPNjHhTTIxrW9pVojScONWPRNwQLZJvPQbNQZVMBoWff8Ru5f70G6xcf9xsNzOow7Yc431wxCuUBX30092Hqd9YX7E2wWETnpZpJoRru1WMDrFtzb4kBCxiMc0WR5atZHZ3s1jM5nzBx0VClmF4YO4W191X0zRzSNPVqsXlO6n0tlYVJYE8WQsWQZSvIewq2aGLhMEgMdMpcmO3UOVUeOJKKeajUNjppq3QGC9KmHrrDBdpZcuR2w+dOX9J3ssfDwTt+4LWjk+UjDyUGpvYwTfdoFUG/Z2Xn9Gk6rcRPCi5C9olvUGIQZSZMrVlbKbxi03LEEdya6oJ44hyYe6Usd9+4NZqy//7I9P5f4xIOR8mcxZruMIaWJK/611fqmXu7bN71b7LLDkAi5C3xnDBoLS1sINtkxQBRR74PwrlMjPZysyrMut1EaqRry8lab/aGi0="

env:
  global:
    - BUILD_NUMBER: "$TRAVIS_BUILD_NUMBER"
    - BINTRAY_USER: napster
    - secure: "TibOvGlMn0dBK97rMpvHtk17iEQszuZJkL6rqc8FoKOmMb36CFdHK7lGUCGHEoYwCl2Cs4OSICWyLhmYwfP623vYLrXfd5fdBbHWaSO1RtQkGK9+roomb80tkYleKBUArWrteYk+uevWA7HxWoQXmoVKD/DvppF6tZsJq2sv8BFQZSE2XDtiQ5QvotD0j4ypSwatZFT73AAGJlxbT3fBrx5gNw6bLJd8ZEdjRTEL+bHPAh+iqURVg3181RcEJQA3N+uAn2dkdByn4TENBLvsr4HuQmkeG0W7yTWIhZZS+t2sbp4i2PrGmEVaGeqc4DqqVSAR522NLOzwfpxXJcRr9xmfQXnt2qPyfK7cZQET/QuRvUIBw1IQo42Bae2Kk0Xhvm45FSOmgYY1YyFNFhdaK/pCbHd5jmp6djTeajeiEaH7Th6LBcDfTrNK8dmL2THvSxsodH2FRwlks+9t3KY7ZwwxXbpwbPb95qYpR8bDqlf9aIE5awNf6LXTi4l97mMNeLoN9e9yXtmDUdjPGkqZqi1nTdFfJH1Qx3RNwufFRVoIfJ7wNQG1W14hTaw6JGXCbEyJkQ5cHFzSW0T+7KH53IicnXbLDneenViDuw21vBwgT+53aHENhgwR5ZpdbhIyUVdGPvxF8udmp2NCmW3ePJrVKwWHKjj+F9I+5g4F49I="
    - DOCKER_USERNAME: napstr
    - secure: "PocnXWMvuXbHSHjoLZOQI0NNze1pFerioQcp/YRYRDUBs2hoKxmu89XEIeoUcpT/ZgJ3t0aUi8iw4XNRVON4khe0sJmAQLqPwXTlHgIVhM6ON3DgC739U6J286lc+w9cWX/awyOVVB4BwASNXlYILQaV9fQy30SBknKdYY9/MIFs+xhYWQuPHONfpWHfLQeVSWKUalD96+Mhj63BlEFNUUrTbVB5vCB4RacBlr63FV7hFkMA3aXDHOSMlnFhZw9ZXi4RmvgCX9XKKaCsiIXinvA32j6slan9WAH43Ay8dd/PLTWu+ExRWjsx/O7T8zhCIHC935ZpKOaeWySBAvN+jMWKlPV0KfJ5SG7yMAx+gjx2M3tJJ5suYIG2bRI0Rc7yeuvK1qJHTZJLKXVj4Ni7qgXIqYNP7RwwObjqzAJWJlYuE8cCstA0V/wXbZ31MmO/TjQfduGRaVm7X+NaxdoHIcn1SB3fgSwbzD1SVa/5B9VQHjmWzEBwa6UKxHtqVFMMPgXB4A5BpvbDZIhu1NKCsG3s3eONd+2YJ9ukF8j03Bs4SBhiNeUd4awAANpLvk80z3BWnX/gnGUkrKFi89jJLNA9DPyMp8TbecsCdU70yLnphTDorOBCDEmk+k5ahfO2ofMutnYOdrlDa5uM4rjF2VAPVViJxvkH6L7MSXT4MCM="
    # WEBHOOK_URL
    - secure: "XiZaI652BCWNG5spHqy3VlOSEZdo6sZfxS2vjBiflAP0/yN84kXXE939osdHIXmZoIeENzioIGGITy21031x6G5R+hZtBWmE7fOi86cr18a4oteW/bb7qJXZpyigRQU8FSMMswjnuSsoQVMGy8SZm+dztjqbZ2TNQ17T2aEb7hV0lNQwN5xlCufZK4J2o6Auj454z8S/k6Qj6g5CeRDvMYOZSg9D4+8uG0DdsC5FV6FhU1sUccVRaqN6h49vVy1H6XBkXuHIZk7+hVeOQ7M/9WoQC/gcHvU3K76kkjlyrrNRtFjP/MDBrJ1NCLqhTZRiP6U6jyljZxFzMZqUNn73bJHWG3iWUOt0Gpkt4VZuT9KGm9VikPZCLtLnEN3yQRitdUFb/T5Kq8kZjvH7QF7LkJIYW+UrgFxwNvE/oLmVrq4SMHIXDkeM/LyQD7qtmtRwTwC8kCF4h6Sg1T722JikSBXbpmsuwtalIbRx0xGFx6g1bf+9KBqcxKMD9g1z/axreHkySh9UzcsDSHL132djTT509bRmaE8hTIh3GPqBYXASzmgGbs51SmcvTxYFSHrAa+kpO1U9M40NHfS4UyNPb++96E6S3QXYDBCzmoYc+oNG4iWjHNrXMpOsQdk+E9w7IJunh4UXCYQfgrrtlZt8Td+VqiPpT+kCqRHRqujZXCc="
    # WEBHOOK_WOLFIA_LOUNGE_URL
    - secure: "vAGmCH4l851StMBCEX+vv3ETEOva2RJxqW2H9NadlTYpgmRGtWoAhMjid4UbVN5HZqAYkucpGf9DC0bzS1LtF1HbKhxEKNs8b4df/zIH7sGbgAe/M5pLr48CEy7N0y4Re3xW+zNQ/kLQt8P+muYtRriufxMKDzZ1vrv85Viy2IdbxsL/RBlxOeh2ZJrns5n5G1JZ+j3zKq3WDYm7c1lxhGwt5+EFhzTGpwplXQcDz52XIFI9/isU8c7xBJzpX6526zG6Zlr30YlrGaWPcTMHrX9e/8faywIaFEoWMZ31xw1Zrx7Pf/yNAfRgMn3JyLsUh+1DRIMFENXvVe8OEjKmzq7SZQ2TBMd83wyUtfWTfyoB4j7lzCH5p+DIN/Z7c76DrwTeD7/9EN929vkfIh4PlXYrjl2ZhkoG60wx1NYG1nrOSBKPIQql2UZBMiDhQaKaXhRDAkSILkNvaSzw24LQpO8/JkJrRv8afevKfqBy0SMaZWeSCLZJDSIwLBdW8leKzBtbPeF9y4q5IvDWBdLVTL2nXYZNcJzG33HCvd5eoq9sF3ER61Hj9NjAauJqEQfxWXt/H+RdsmITN4xCJB0sWzBQ60ik2mD01dqBkEUReeK6fZBQ4bsrxX7PbpAmwOYK+659eoJe5Q2Ds98GXmUDX3nuFwW9yAuhOv6W2l62CqM="

language: java

# See https://github.com/travis-ci/docs-travis-ci-com/pull/611#issuecomment-321394366
before_cache:
  - rm -fr $HOME/.gradle/caches/build-cache-1/
  - rm -fr $HOME/.gradle/caches/journal-1/
  - rm -f  $HOME/.gradle/caches/modules-2/metadata-*/module-metadata.bin
  - rm -f  $HOME/.gradle/caches/modules-2/metadata-*/resource-at-url.bin
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -f  $HOME/.gradle/caches/*/executionHistory/executionHistory.lock
  - rm -f  $HOME/.gradle/caches/*/fileContent/fileContent.lock
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock
  - rm -f  $HOME/.gradle/caches/*/fileHashes/resourceHashesCache.bin
  - rm -f  $HOME/.gradle/caches/*/javaCompile/javaCompile.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  yarn: true
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle/wrapper"
    - "$HOME/.gradle/caches"
    - "$HOME/.sonar/cache"

jobs:
  include:
    - stage: build
      jdk: openjdk11
      before_script:
        - java -Xmx32m -version
        # to determine version
        - git fetch --unshallow
      script:
        - ./gradlew assemble --info
      after_failure:
        - wget https://raw.githubusercontent.com/napstr/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh failure $WEBHOOK_URL
        - ./send.sh failure $WEBHOOK_WOLFIA_LOUNGE_URL

    - stage: test
      jdk: openjdk11
      before_script:
        - java -Xmx32m -version
        # for full sonar cloud blame information
        - git fetch --unshallow
      script:
        - ./gradlew sonarqube
      after_success:
        - ./gradlew bootJar
        - IMAGE_TAG=$(echo ${TRAVIS_BRANCH} | sed -e 's/\//_/g')
        - CI_IMAGE_NAME=$DOCKER_USERNAME/wolfia:ci-$IMAGE_TAG
        - echo $CI_IMAGE_NAME
        - docker build -t "$CI_IMAGE_NAME" -f docker/Dockerfile .
        - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin
        - docker push $CI_IMAGE_NAME
        - docker logout
        # Discord Webhook
        - wget https://raw.githubusercontent.com/napstr/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL
        - ./send.sh success $WEBHOOK_WOLFIA_LOUNGE_URL
      after_failure:
        - wget https://raw.githubusercontent.com/napstr/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh failure $WEBHOOK_URL
        - ./send.sh failure $WEBHOOK_WOLFIA_LOUNGE_URL

    - stage: publish
      jdk: openjdk11
      script:
        - ./gradlew bintrayUpload --info
        - IMAGE_TAG=$(echo ${TRAVIS_BRANCH} | sed -e 's/\//_/g')
        - CI_IMAGE_NAME=$DOCKER_USERNAME/wolfia:ci-$IMAGE_TAG
        - echo $CI_IMAGE_NAME
        - PUBLIC_IMAGE_NAME=$DOCKER_USERNAME/wolfia:$IMAGE_TAG
        - echo $PUBLIC_IMAGE_NAME
        - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin
        - docker pull $CI_IMAGE_NAME
        - docker tag $CI_IMAGE_NAME $PUBLIC_IMAGE_NAME
        - docker push $PUBLIC_IMAGE_NAME
        - docker logout

stages:
  - build
  - test
  - name: publish
    if: tag IS present
