---

wolfia:
  debug:            true   # Some things are different. Set to false to properly run the bot.
  discordToken:     ""     # Discord bot token
  logChannelId:     0      # Id of a channel where to post general bot activity like games starting and ending.
  webAdmin:         ""     # User name to access any secured web endpoints, for example feature flag settings
  webPass:          ""     # Password to access any secured web endpoints, for example feature flag settings

database:
  jdbcUrl:          ""     # Postgres database. When running with the bundled docker-compose file, set to jdbc:postgresql://db:5432/wolfia?user=wolfia

oauth2:
  clientId:         ""
  clientSecret:     ""
  baseRedirectUrl:  ""

server:
  port:             4567   # Port of Wolfia's API.
  servlet:
    application-display-name: "Wolfia"

sentry:
  dsn:              ""     # Error aggregation service. See https://sentry.io

spring:
  main:
    lazy-initialization: true
  output:
    ansi:
      enabled: always

togglz:
  enabled: true
  feature-enums: space.npstr.wolfia.domain.FeatureFlag
  feature-manager-name: default
  console:
    enabled: true
    path: /api/togglz
    secured: true
    use-management-port: false

logging:
  file:
    name: './logs/wolfia.log'
    max-history: 30
    max-size: 1GB

  level:
    root: INFO
    space.npstr: DEBUG
