---

wolfia:
  debug:            true   # Some things are different. Set to false to properly run the bot.
  discordToken:     ""     # Discord bot token
  logChannelId:     0      # Id of a channel where to post general bot activity like games starting and ending.

database:
  jdbcUrl:          ""     # Postgres database. When running with the bundled docker-compose file, set to jdbc:postgresql://db:5432/wolfia?user=wolfia

server:
  port:             4567   # Port of Wolfia's API.

sentry:
  dsn:              ""     # Error aggregation service. See https://sentry.io

spring:
  output:
    ansi:
      enabled: always

logging:
  file:
    name: './logs/wolfia.log'
    max-history: 30
    max-size: 1GB

  level:
    root: INFO
    space.npstr: DEBUG
