version: '3'
services:

  db:
    image: napstr/wolfia-postgres:master
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      #See the README of the database docker image
      - ROLE=wolfia
      - DB=wolfia
      - BACKUP_DB=wolfia
      - BACKUP_APPNAME=wolfia
      - BACKUP_BUCKET_DAILY=fill_this_out
      - BACKUP_BUCKET_WEEKLY=fill_this_out
      - BACKUP_BUCKET_MONTHLY=fill_this_out
      - BACKUP_ACCOUNT_ID=fill_this_out
      - BACKUP_APP_KEY=fill_this_out

  bot:
    image: napstr/wolfia:master
    restart: on-failure:3
    depends_on:
      - db
    ports:
      - 4567:4567
    volumes:
      - ./wolfia.yaml:/opt/wolfia/wolfia.yaml
      - ./logs:/opt/wolfia/logs
      - ./logs/gc:/opt/wolfia/logs/gc
    stop_grace_period: 7200s #should really be enough to finish all games
    entrypoint:
      - java
      - -jar
      - -Xmx2g
      - -XX:+HeapDumpOnOutOfMemoryError
      - -XX:HeapDumpPath=emergencydump.hprof
      - -Xlog:gc*:logs/gc/gc-%t.log::filesize=1g
      - -XX:+UseG1GC
      - -XX:+ParallelRefProcEnabled
      - -XX:+UseStringDeduplication
      - wolfia.jar
